services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./.docker/DockerFile-nuxt
      args:
        ENV: ${APP_PORT_PRODUCTION}
    tty: true
    command: sh -c "npx next start -p ${APP_PORT_PRODUCTION}"
    ports:
      - ${APP_PORT_PRODUCTION}:${APP_PORT_PRODUCTION}
    env_file: .env
    restart: always

  # app-nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - app
  #   restart: always
