FROM node:16-alpine

RUN mkdir app
COPY . ./app/

WORKDIR /app

# ARG NODE_ENV=development
# ENV NODE_ENV=${NODE_ENV}

RUN npm install --legacy-peer-deps

EXPOSE 3000

RUN npm run build

EXPOSE ${APP_PORT_PRODUCTION}


# ENTRYPOINT ["tail", "-f", "/dev/null"]
