FROM node:16-alpine

RUN mkdir app
COPY . ./app/

WORKDIR /app

# ARG NODE_ENV=development
# ENV NODE_ENV=${NODE_ENV}

RUN npm install --legacy-peer-deps

RUN npm run build

ARG ENV
EXPOSE ${ENV}

# ENTRYPOINT ["tail", "-f", "/dev/null"]