// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'I:fluent:poll16Filled': typeof import('~icons/fluent/poll16-filled')['default']
    'I:fluent:poll48Regular': typeof import('~icons/fluent/poll48-regular')['default']
    'I:fluent:vote20Filled': typeof import('~icons/fluent/vote20-filled')['default']
    'I:ic:baselineLogIn': typeof import('~icons/ic/baseline-log-in')['default']
    'I:ic:baselineLogOut': typeof import('~icons/ic/baseline-log-out')['default']
    'I:icBaselineDarkMode': typeof import('~icons/ic/baseline-dark-mode')['default']
    'I:logos:facebook': typeof import('~icons/logos/facebook')['default']
    'I:logos:googleIcon': typeof import('~icons/logos/google-icon')['default']
    'I:logos:linkedinIcon': typeof import('~icons/logos/linkedin-icon')['default']
    'I:materialSymbols:chatRounded': typeof import('~icons/material-symbols/chat-rounded')['default']
    'I:materialSymbols:info': typeof import('~icons/material-symbols/info')['default']
    'I:materialSymbols:questionMark': typeof import('~icons/material-symbols/question-mark')['default']
    'I:materialSymbols:restaurant': typeof import('~icons/material-symbols/restaurant')['default']
    'I:mdi:officeBuilding': typeof import('~icons/mdi/office-building')['default']
    'I:mdi:plus': typeof import('~icons/mdi/plus')['default']
    'I:mdi:send': typeof import('~icons/mdi/send')['default']
    'I:mdi:trash': typeof import('~icons/mdi/trash')['default']
    'I:mdi:user': typeof import('~icons/mdi/user')['default']
    'I:mdiWhiteBalanceSunny': typeof import('~icons/mdi/white-balance-sunny')['default']
    'I:ph:chatTeardropDotsFill': typeof import('~icons/ph/chat-teardrop-dots-fill')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NAvatarGroup: typeof import('naive-ui')['NAvatarGroup']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEl: typeof import('naive-ui')['NEl']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NProgress: typeof import('naive-ui')['NProgress']
    NResult: typeof import('naive-ui')['NResult']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
